# Generated by Django 2.0.2 on 2018-07-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20180710_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.CharField(max_length=10000),
        ),
    ]
