# Generated by Django 2.0.2 on 2018-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('institute', models.CharField(max_length=65)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
