# Generated by Django 2.0.2 on 2018-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0002_auto_20180710_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
